'use strict';
const assert=require('node:assert/strict');
const {memoryFixture}=require('./interaction_test_fixture');
const SPECS=require('./persuasion_specs.json').methods;
function fixture(current=false) {
 const f=memoryFixture(current),{ptr,object,klass,fields,method,block,alloc}=f;
 const panel=object('Game','NpcPersuadePanel'),npc=object('Game.Model','NpcModel'),world=object('Game.Model','GameWorldModel'),player=object('Game.Model','PlayerModel'),input=object('Game','DialogueInputPanel');
 const pf=[['_subscribedNpc',0x04005425,0x12,0x158],['_npcId',0x0400542d,0x11,0x188],['_topicId',0x0400542e,0x11,0x18c],['DialogueInput',0x0400541d,0x12,0x118],['_persuadeEnded',0x04005427,2,0x168],['_persuadeResultNotified',0x04005428,2,0x169],['_settlementDelayCts',0x04005429,0x12,0x170],['_settlementIsWin',0x0400542a,2,0x178],['_userInitiatedClose',0x0400542b,2,0x179],['_peekLoadingCo',0x04005432,0x12,0x1a8],['_peekRequestToken',0x04005433,8,0x1b0],['_isFlowAlive',0x0400542c,0x15,0x180],['_actionOnWin',0x0400542f,0x12,0x190],['_actionOnLose',0x04005430,0x12,0x198],['_actionOnClose',0x04005431,0x12,0x1a0]];fields(panel.readPointer(),pf);
 fields(npc.readPointer(),[['<IsProcessingChatMessage>k__BackingField',0x0400a8dc,2,0xa8],['<IsSummarizingChatHistory>k__BackingField',0x0400a8dd,2,0xa9],['<NpcCfgId>k__BackingField',0x0400a8fe,0x11,0x150],['<GameWorld>k__BackingField',0x0400a901,0x12,0x168],['IsProcessingPersuadeMessage',0x0400a8e8,2,0xe8],['<PersuadeSessionId>k__BackingField',0x0400a8ee,8,0x100],['_persuadeProcessingToken',0x0400a8e9,8,0xec],['<LastPersuadeEndReason>k__BackingField',0x0400a8e2,0x11,0xc4],['<CurrentPersuadeTopicId>k__BackingField',0x0400a8e3,0x11,0xc8],['<PersuadeRound>k__BackingField',0x0400a8e4,8,0xcc],['<PersuadeEmotionValue>k__BackingField',0x0400a8e6,8,0xd8],['OnPersuadeEnded',0x0400a8f2,0x15,0x120],['<PersuadeChatMessages>k__BackingField',0x0400a8e5,0x15,0xd0],['_persuadeLedger',0x0400a8eb,0x15,0xf8]]);
 fields(world.readPointer(),[['<PlayerModel>k__BackingField',0x0400a7e6,0x12,24],['<NpcModels>k__BackingField',0x0400a7ea,0x15,0x38]]);fields(input.readPointer(),[['m_CanSubmit',0x04004c28,2,0x128],['m_SubmitAvailable',0x04004c29,2,0x129]]);
 panel.add(16).writePointer(1);for(const o of [0x42,0x43,0x92])panel.add(o).writeU8(1);panel.add(0x158).writePointer(npc);panel.add(0x118).writePointer(input);panel.add(0x188).writeS32(100);panel.add(0x18c).writeS32(200);panel.add(0x1b0).writeS32(5);
 npc.add(0x150).writeS32(100);npc.add(0x168).writePointer(world);npc.add(0xc8).writeS32(200);npc.add(0x100).writeS32(3);npc.add(0xec).writeS32(7);world.add(24).writePointer(player);input.add(16).writePointer(1);input.add(0x128).writeU8(1);
 const map=f.concurrent('npc',[['npc-uuid',npc.toString()]]);world.add(0x38).writePointer(map.address);
 const closure=object('','<>c__DisplayClass5_0'),command=object('Game','MiniGamePersuadeCommand'),context=object('A1.Flow','ProcContext'),source=object('System.Threading','CancellationTokenSource');
 fields(closure.readPointer(),[['notified',0x04005bfa,2,16],['win',0x04005bfb,2,17],['<>4__this',0x04005bfd,0x12,32],['ctx',0x04005bfe,0x12,40]]);fields(command.readPointer(),[['_npcId',0x04005bf7,0x11,16],['_topicId',0x04005bf8,0x11,20],['_subId',0x04005bf9,0x15,24]]);fields(context.readPointer(),[['<Ct>k__BackingField',0x040000d0,0x11,16],['<ActivationId>k__BackingField',0x040000d1,8,24],['_endedNotified',0x040000d8,2,0x78]]);fields(source.readPointer(),[['_state',0x04000a46,8,32],['_disposed',0x04000a48,2,40]]);
 closure.add(32).writePointer(command);closure.add(40).writePointer(context);command.add(16).writeS32(100);command.add(20).writeS32(200);command.add(24).writeU8(1);command.add(28).writeS32(300);context.add(16).writePointer(source);context.add(24).writeS32(2);
 const dc=klass('System','Delegate',0x78),mc=klass('System','MulticastDelegate',0x80);fields(dc,[['method_ptr',0x04000762,0x18,16],['method',0x04000765,0x18,40],['method_code',0x04000768,0x18,64]]);fields(mc,[['delegates',0x04000790,0x1d,0x78]]);mc.add(0x58).writePointer(dc);
 const methods={};for(const key of ['win','lose','close','alive','ended'])methods[key]=method(key==='ended'?panel.readPointer():closure.readPointer(),{...SPECS[key],static:false,params:key==='ended'?[2,14]:[]});
 function delegate(key,target){const p=object('System','Action');p.readPointer().add(0x58).writePointer(mc);p.add(16).writePointer(f.base.add(f.variant(SPECS[key]).rva));p.add(40).writePointer(methods[key].address);p.add(64).writePointer(target);block(p,0x300);return {address:p.toString(),code:p.add(16).readPointer().toString(),method_info:methods[key].address.toString(),target:target.toString(),delegates:'0x0'};}
 const callbacks={};for(const [key,offset]of [['alive',0x180],['win',0x190],['lose',0x198],['close',0x1a0]]){callbacks[key]=delegate(key,closure);panel.add(offset).writePointer(callbacks[key].address);}
 const event=delegate('ended',panel);npc.add(0x120).writePointer(event.address);const chat=object('System.Collections.Generic','List`1'),ledger=object('System.Collections.Generic','List`1');npc.add(0xd0).writePointer(chat);npc.add(0xf8).writePointer(ledger);
 const topic=object('LubanDatas.data','NpcPersuadeTopic'),entry=object('LubanDatas.data','NpcInteractGameEntry');fields(topic.readPointer(),[['<id>k__BackingField',0x0400182b,0x11,16],['<maxRounds>k__BackingField',0x0400182d,8,32],['<npcId>k__BackingField',0x04001832,0x11,0x48],['<autoExitDelayMs>k__BackingField',0x04001833,0x15,0x4c]]);fields(entry.readPointer(),[['<npcId>k__BackingField',0x040017cd,0x11,16],['<subId>k__BackingField',0x040017ce,0x11,20],['<interactGameType>k__BackingField',0x040017d4,0x11,0x40],['<interactGameParam>k__BackingField',0x040017d5,8,0x44]]);
 topic.add(16).writeS32(200);topic.add(32).writeS32(3);topic.add(0x48).writeS32(100);topic.add(0x4c).writeU8(1);topic.add(0x50).writeS32(10000);entry.add(16).writeS32(100);entry.add(20).writeS32(300);entry.add(0x40).writeS32(2);entry.add(0x44).writeS32(200);
 const manager=object('Game','UIManager'),reg=object('System.Collections.Generic','Dictionary`2'),entries=object('','Entry[]');reg.add(24).writePointer(entries);reg.add(32).writeS32(1);entries.add(24).writePointer(3);entries.add(48).writePointer(panel);
 const links=[];for(const [i,v]of [manager,reg,entries,panel,world,player,npc,input].entries()){const a=i===0?f.base.add(0x8157868):alloc(8);a.writePointer(v);f.addAnchor(a,8);links.push({address:a.toString(),expected:v.toString()});}
 for(const p of [panel,npc,world,player,input,closure,command,context,source,chat,ledger,topic,entry,manager,reg,entries])block(p,0x300);
 const m={round_key:'b'.repeat(64),panel:panel.toString(),panel_class:panel.readPointer().toString(),npc:npc.toString(),npc_class:npc.readPointer().toString(),world:world.toString(),player:player.toString(),npc_id:100,topic_id:200,sub_id:300,session_id:3,processing_token:7,peek_token:5,input_panel:input.toString(),input_class:input.readPointer().toString(),
  flow:{closure:closure.toString(),closure_class:closure.readPointer().toString(),command:command.toString(),command_class:command.readPointer().toString(),context:context.toString(),context_class:context.readPointer().toString(),source:source.toString(),source_class:source.readPointer().toString(),activation_id:2,sub_id:300,notified:false,ended:false,cancelled:false,callbacks},
  membership:{dictionary_descriptor:map,uuid:'npc-uuid',node:map.items[0].node,npc:npc.toString(),npc_id:100},event:event.address,event_callbacks:[event],chat:chat.toString(),ledger:ledger.toString(),config:{topic_config:topic.toString(),entry_config:entry.toString(),max_rounds:3,exit_delay_ms:10000},
  manager:manager.toString(),registry_links:links,registry:{dictionary:reg.toString(),entries:entries.toString(),count:1,count_address:reg.add(32).toString()},post_stable_anchors:f.request.anchors.filter(a=>links.some(l=>l.address===a.address))};
 const result=method(npc.readPointer(),{...SPECS.result,static:false},[null,klass('Game.Model','PersuadeEndReason',20)]);
 Object.assign(f.request,{operation:'persuasion_success',persuasion:m,method_info:result.address.toString(),method_token:f.variant(SPECS.result).token,method_rva:f.variant(SPECS.result).rva,parameter_count:2});
 const calls=[];f.options.invoke=(mi,target,args,exception)=>{calls.push(mi.toString());assert.ok(mi.equals(result.address));assert.ok(target.equals(npc));assert.equal(args.readPointer().readU8(),1);assert.equal(args.add(8).readPointer().readS32(),1);
  if(f.options.throw)throw Error('native failure');exception.writePointer(f.options.exception?1:0);
  if(!f.options.noChange){panel.add(0x168).writeU8(1);panel.add(0x178).writeU8(1);panel.add(0x170).writePointer(source);panel.add(0x1b0).writeS32(6);input.add(0x128).writeU8(0);npc.add(0xc4).writeS32(1);npc.add(0xc8).writeS32(0);npc.add(0xcc).writeS32(0);npc.add(0xd8).writeS32(0);}
  if(f.options.after)f.options.after();return ptr(f.options.nonVoid?1:0);
 };
 f.sync();return {...f,m,panel,npc,world,player,input,closure,command,context,source,topic,entry,map,result,methods,event,calls};
}
let count=0;function test(n,fn){try{fn();count++;}catch(e){e.message=n+': '+e.message;throw e;}}
function rejected(f){const r=f.submit();assert.equal(r.status,'rejected',JSON.stringify(r));assert.equal(r.called,false);assert.equal(f.calls.length,0);return r;}
function unknown(f){const r=f.submit();assert.equal(r.status,'unknown',JSON.stringify(r));assert.equal(r.called,true);assert.equal(f.calls.length,1);assert.throws(()=>f.api.reset(f.request.token));return r;}
test('normal success calls model once, retaining countdown not reward claim',()=>{const f=fixture(),r=f.submit();assert.equal(r.status,'completed',JSON.stringify(r));assert.equal(r.native_won,true);assert.equal(r.normal_countdown,true);assert.equal(f.panel.add(0x169).readU8(),0);f.run();assert.equal(f.calls.length,1);});
test('same round fresh token cannot repeat',()=>{const f=fixture();assert.equal(f.submit().status,'completed');f.api.reset(f.request.token);f.request.token='fresh';f.sync();const r=f.submit();assert.equal(r.status,'rejected');assert.equal(f.calls.length,1);});
for(const [label,obj,offset,value]of [['chat processing','npc',0xa8,1],['history summarizing','npc',0xa9,1],['AI processing','npc',0xe8,1],['input await','input',0x128,0],['ended panel','panel',0x168,1],['closed panel','panel',0x179,1],['notified panel','panel',0x169,1],['flow notified','closure',16,1],['context ended','context',0x78,1],['CTS disposed','source',40,1]])test(label+' refuses',()=>{const f=fixture();f[obj].add(offset).writeU8(value);f.sync();rejected(f);});
for(const status of [2,3,4,-1])test('CTS state '+status+' refuses',()=>{const f=fixture();f.source.add(32).writeS32(status);f.sync();rejected(f);});
test('uncancellable context permitted',()=>{const f=fixture();f.context.add(16).writePointer(0);f.m.flow.source='0x0';f.m.flow.source_class='0x0';f.sync();assert.equal(f.submit().status,'completed');});
test('empty input may still succeed',()=>{const f=fixture();assert.equal(f.input.add(0x129).readU8(),0);assert.equal(f.submit().status,'completed');});
for(const [label,obj,offset,value]of [['topic','npc',0xc8,201],['session','npc',0x100,4],['processing token','npc',0xec,8],['peek token','panel',0x1b0,6],['command subID','command',28,301]])test('mismatched '+label+' refuses',()=>{const f=fixture();f[obj].add(offset).writeS32(value);f.sync();rejected(f);});
test('peek coroutine prevents submit',()=>{const f=fixture();f.panel.add(0x1a8).writePointer(1);f.sync();rejected(f);});
test('stale snapshot refuses before invoke',()=>{const f=fixture();f.npc.add(0x100).writeS32(4);rejected(f);});
test('unregistered panel refuses',()=>{const f=fixture();f.ptr(f.m.registry.entries).add(48).writePointer(0);f.sync();rejected(f);});
test('changed callback target refuses even updated anchor',()=>{const f=fixture();f.ptr(f.m.flow.callbacks.win.address).add(64).writePointer(f.npc);f.sync();rejected(f);});
test('missing model to panel event refuses',()=>{const f=fixture();f.m.event_callbacks[0].target=f.npc.toString();f.ptr(f.event.address).add(64).writePointer(f.npc);f.sync();rejected(f);});
test('wrong native enum refuses',()=>{const f=fixture();f.result.params[1].add(10).writeU8(8);rejected(f);});
test('normal short topic delay supported',()=>{const f=fixture();f.topic.add(0x50).writeS32(1000);f.m.config.exit_delay_ms=1000;f.sync();assert.equal(f.submit().status,'completed');});
for(const option of ['throw','exception','noChange','nonVoid'])test('native '+option+' stays unknown',()=>{const f=fixture();f.options[option]=true;unknown(f);});
test('callback replaces save root produces unknown',()=>{const f=fixture();f.options.after=()=>f.ptr(f.m.registry_links[4].address).writePointer(0);unknown(f);});
test('callback increments session produces unknown',()=>{const f=fixture();f.options.after=()=>f.npc.add(0x100).writeS32(4);unknown(f);});
test('callback replaces closure produces unknown',()=>{const f=fixture();f.options.after=()=>f.ptr(f.m.flow.callbacks.win.address).add(64).writePointer(f.npc);unknown(f);});
test('cancel before dispatch leaves model untouched',()=>{const f=fixture();f.api.submit(f.request);f.api.cancel();f.run();assert.equal(f.calls.length,0);});
test('current renumbered callbacks retain their roles',()=>{const f=fixture(true);const r=f.submit();assert.equal(r.status,'completed',JSON.stringify(r));assert.equal(f.calls.length,1);});
test('current callback legacy token mixed in refused',()=>{const f=fixture(true);f.methods.win.address.add(0x48).writeS32(SPECS.win.token);f.sync();rejected(f);});
console.log('Persuasion production bridge tests passed: '+count);
module.exports={fixture};
